# # Runs the Node.js script that generates the index.json file
# # -Tom16

# name: "Check Padanyi Website status"

# on:
#   workflow_dispatch:
#   push:
#     branches: [main]
#   schedule:
#     - cron: "*/30 * * * *"

# permissions:
#     contents: write
#     pull-requests: read

# jobs:
#   update-time:
#     runs-on: "ubuntu-latest"
#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18.12.x
#           cache: npm
#           cache-dependency-path: package-lock.json
#       - name: Run index.js
#         run: node index.js
